version: "3"
services:
  app:
    container_name: RTM_CONTAINER_NAME_REPLACE
    build:
      context: ./docker-services/app
      dockerfile: Dockerfile
    environment:
      - "YOUR_ENVIRONMENT_VAR=true"
    volumes:
      - ./RTM_APP_DIR_REPLACE:/myapp/
#    ports: # host-port:container-port
#      - 3000:3000
    # overwrite default command
    command: sh -c 'cd /myappp ; bundle install; rm  /myapp/tmp/pids/server.pid; rails server -b 0.0.0.0'
#    restart: always
